import { expect, test } from "@playwright/test";

test.describe("multitenant isolation", () => {
  test("user A patient not visible to user B (placeholder)", async ({
    page,
  }) => {
    // Placeholder: requires programmatic login and API calls to create patient
    await page.goto("http://localhost:3000");
    await expect(page).toHaveTitle(/Doutor Agenda/i);
  });
});
test("user A patient not visible to user B", async ({ browser }) => {
  // Requires storage states generated by tests/e2e/00_setup.spec.ts
  const userAState = "tests/.auth/userA.json";
  const userBState = "tests/.auth/userB.json";

  // Create a patient as user A via UI
  const contextA = await browser.newContext({ storageState: userAState });
  const pageA = await contextA.newPage();
  await pageA.goto("/appointments");
  // Navigate to new patient form (placeholder selectors)
  await pageA.click("text=Pacientes");
  await pageA.click("text=Novo paciente");
  await pageA.fill('input[placeholder="Nome"]', "Patient A");
  await pageA.fill('input[placeholder="Telefone"]', "11999999999");
  await pageA.click("text=Salvar");
  // Give server time to persist
  await pageA.waitForTimeout(1000);
  await contextA.close();

  // Now open as user B and assert patient A not visible
  const contextB = await browser.newContext({ storageState: userBState });
  const pageB = await contextB.newPage();
  await pageB.goto("/patients");
  const content = await pageB.content();
  expect(content).not.toContain("Patient A");
  await contextB.close();
});
